loki-stack:
  loki:
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
    auth_enabled: false
    write:
      persistence:
        size: 15Gi
        storageClass: default
