{{- if .Values.tls.enableTLSComponents -}}
{{- if .Values.tls.dnsClientSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.dnsClientSecretName }}
  namespace: {{ .Release.Namespace}}
type: Opaque
stringData:
  {{ .Values.tls.dnsClientSecretKey }}: {{ .Values.tls.dnsClientSecretValue }}
{{- end -}}
{{- end -}}
