apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress/ingress-argocd.yaml

patches:
  - path: configmap/argo-cm.yaml
  - path: configmap/argo-notification-channels.yaml
  - path: secrets/argo-notification-secrets.yaml
