apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    p, role:minimal, applications, *, */*, deny
    p, role:minimal, clusters, get, *, allow
    p, role:minimal, repositories, get, *, allow
    g, catenax-ng:argocdadmins, role:admin
    g, catenax-ng:beta-admins, role:admin
