apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
type: Opaque
stringData:
  argocdadmins-teams-channel: <path:devsecops/data/apps/argocd/argocd-notifications-secret#argocd-notification-teams-channel-url>

