apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.24/manifests/ha/install.yaml
  - vault-plugin/vault-plugin-cm.yaml # AVP sidecar configuration
  - avp-rbac-secret-access.yaml # grant avp access to secret with AVP configuration

patches:
  - path: argocd-cm.yaml
  - path: argocd-rbac-cm.yaml
  - path: enable-webterminal.yaml
  - path: vault-plugin/argo-repo-server-sidecars.yaml # add AVP sidecars to reposerver deployment
