apiVersion: v2
name: catena-cluster-stack
description: A Helm chart installing the default stack components for k8s clusters running at the Catena-X consortium

type: application

version: 0.1.0

appVersion: "0.1.0"

dependencies:
  - name: ingress-nginx
    alias: ingress-nginx
    version: 4.2.3
    repository: https://kubernetes.github.io/ingress-nginx
  - name: cert-manager
    alias: certmanager
    version: 1.10.0
    repository: https://charts.jetstack.io
    condition: tls.enableTLSComponents
  - name: kube-prometheus-stack
    alias: kube-prometheus-stack
    version: 35.5.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki
    alias: loki
    version: 3.10.0
    repository: https://grafana.github.io/helm-charts
  - name: reflector
    version: 6.1.47
    repository: https://emberstack.github.io/helm-charts
