apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beta-config
  namespace: argocd
  labels:
    environment: beta
spec:
  project: default
  source:
    repoURL: https://github.com/catenax-ng/product-onboarding
    targetRevision: HEAD
    path: cluster/beta
    plugin:
      name: argocd-vault-plugin-kustomize

  destination:
    name: beta
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
