apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-config
  namespace: argocd
  labels:
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/catenax-ng/product-onboarding
    targetRevision: HEAD
    path: cluster/dev
    plugin:
      name: argocd-vault-plugin-kustomize

  destination:
    name: dev
    namespace: argocd
