apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stable-config
  namespace: argocd
  labels:
    environment: stable
spec:
  project: default
  source:
    repoURL: https://github.com/catenax-ng/product-onboarding
    targetRevision: HEAD
    path: cluster/stable
    plugin:
      name: argocd-vault-plugin-kustomize

  destination:
    name: stable
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
